spring:
  application:
    name: prescricao-api
  cloud:
    config:
      enabled: false
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:h2:mem:todolist
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
header:
  login: xto-xtz
prescription:
  status:
    waiting: 0
    approved: 1
    rejected: 2
